/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author migue
 */
public class MetodosNumericos extends javax.swing.JFrame {

    /**
     * Creates new form MetodosNumericos
     */
   public MetodosNumericos() {
    initComponents();
    configurarComponentes();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("tamaño");

        jButton1.setText("crear tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("metodo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("tolerancia:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("max iteraciones:");

        jButton2.setText("Resolver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         crearTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resolver();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodosNumericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodosNumericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodosNumericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodosNumericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodosNumericos().setVisible(true);
            }
        });
    }
    
    private javax.swing.table.DefaultTableModel modeloCoeficientes;
    private javax.swing.table.DefaultTableModel modeloResultados;
    

private void configurarComponentes() {
    
    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(3, 1, 25, 1));
   
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"Eliminacion de Gauss", "Gauss-Jordan", "Gauss-Seidel"}
    ));
    jTextField1.setText("0.0001");
    jTextField2.setText("100");
    
    modeloCoeficientes = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modeloResultados = (javax.swing.table.DefaultTableModel) jTable2.getModel();
    
   
    crearTabla();
}
    
   private void crearTabla() {
    int n = (Integer) jSpinner1.getValue();
    
    modeloCoeficientes.setRowCount(0);
    modeloCoeficientes.setColumnCount(0);
    
    for (int i = 0; i < n; i++) {
        modeloCoeficientes.addColumn("x" + (i + 1));
    }
    modeloCoeficientes.addColumn("b");
    
    for (int i = 0; i < n; i++) {
        Object[] fila = new Object[n + 1];
        for (int j = 0; j <= n; j++) {
            fila[j] = "0";
        }
        modeloCoeficientes.addRow(fila);
    }
}
    
   private void limpiar() {
    crearTabla();
    modeloResultados.setRowCount(0);
    modeloResultados.setColumnCount(0);
}
   
  

   private void resolver() {
    try {
        int n = modeloCoeficientes.getRowCount();
        double[][] A = new double[n][n];
        double[] b = new double[n];
        
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                A[i][j] = Double.parseDouble(jTable1.getValueAt(i, j).toString());
            }
            b[i] = Double.parseDouble(jTable1.getValueAt(i, n).toString());
        }
        
        String metodo = (String) jComboBox1.getSelectedItem();
        double[] solucion = null;
        
     
        modeloResultados.setRowCount(0);
        modeloResultados.setColumnCount(0);
        
        if (metodo.equals("Eliminacion de Gauss")) {
            solucion = eliminacionGauss(A, b);
            mostrarResultados(solucion, null);
        } else if (metodo.equals("Gauss-Jordan")) {
            solucion = gaussJordan(A, b);
            mostrarResultados(solucion, null);
        } else if (metodo.equals("Gauss-Seidel")) {
            double tol = Double.parseDouble(jTextField1.getText());
            int maxIter = Integer.parseInt(jTextField2.getText());
            solucion = gaussSeidel(A, b, tol, maxIter);
        }
        
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}
    
    private void mostrarResultados(double[] sol, String[][] iteraciones) {
    modeloResultados.setRowCount(0);
    modeloResultados.setColumnCount(0);
    

    if (iteraciones != null && iteraciones.length > 0) {
        
        modeloResultados.addColumn("k");
        int numVariables = sol.length;
        for (int i = 0; i < numVariables; i++) {
            modeloResultados.addColumn("x" + (i + 1) + "(k)");
        }
        modeloResultados.addColumn("|x(k+1) - x(k)|");
        
       
        for (String[] fila : iteraciones) {
            modeloResultados.addRow(fila);
        }
    } else {
        
        modeloResultados.addColumn("Variable");
        modeloResultados.addColumn("Valor");
        
        for (int i = 0; i < sol.length; i++) {
            modeloResultados.addRow(new Object[]{"x" + (i+1), String.format("%.8f", sol[i])});
        }
    }
    
 
    for (int i = 0; i < jTable2.getColumnModel().getColumnCount(); i++) {
        jTable2.getColumnModel().getColumn(i).setPreferredWidth(100);
    }
}
    private double[] eliminacionGauss(double[][] A, double[] b) {
        int n = A.length;
        double[][] m = new double[n][n + 1];
        
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                m[i][j] = A[i][j];
            }
            m[i][n] = b[i];
        }
        
        for (int k = 0; k < n - 1; k++) {
            int maxFila = k;
            for (int i = k + 1; i < n; i++) {
                if (Math.abs(m[i][k]) > Math.abs(m[maxFila][k])) {
                    maxFila = i;
                }
            }
            
            if (maxFila != k) {
                double[] temp = m[k];
                m[k] = m[maxFila];
                m[maxFila] = temp;
            }
            
            for (int i = k + 1; i < n; i++) {
                double factor = m[i][k] / m[k][k];
                for (int j = k; j <= n; j++) {
                    m[i][j] -= factor * m[k][j];
                }
            }
        }
        
        double[] x = new double[n];
        for (int i = n - 1; i >= 0; i--) {
            x[i] = m[i][n];
            for (int j = i + 1; j < n; j++) {
                x[i] -= m[i][j] * x[j];
            }
            x[i] /= m[i][i];
        }
        
        return x;
    }
    
    private double[] gaussJordan(double[][] A, double[] b) {
        int n = A.length;
        double[][] m = new double[n][n + 1];
        
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                m[i][j] = A[i][j];
            }
            m[i][n] = b[i];
        }
        
        for (int k = 0; k < n; k++) {
            int maxFila = k;
            for (int i = k + 1; i < n; i++) {
                if (Math.abs(m[i][k]) > Math.abs(m[maxFila][k])) {
                    maxFila = i;
                }
            }
            
            if (maxFila != k) {
                double[] temp = m[k];
                m[k] = m[maxFila];
                m[maxFila] = temp;
            }
            
            double pivote = m[k][k];
            for (int j = 0; j <= n; j++) {
                m[k][j] /= pivote;
            }
            
            for (int i = 0; i < n; i++) {
                if (i != k) {
                    double factor = m[i][k];
                    for (int j = 0; j <= n; j++) {
                        m[i][j] -= factor * m[k][j];
                    }
                }
            }
        }
        
        double[] x = new double[n];
        for (int i = 0; i < n; i++) {
            x[i] = m[i][n];
        }
        
        return x;
    }
    
   private double[] gaussSeidel(double[][] A, double[] b, double tol, int maxIter) {
    int n = A.length;
    double[] x = new double[n];
    double[] xAnt = new double[n];
    
    
    java.util.ArrayList<String[]> iteraciones = new java.util.ArrayList<>();
    
   
    String[] fila0 = new String[n + 2];
    fila0[0] = "0";
    for (int i = 0; i < n; i++) {
        fila0[i + 1] = String.format("%.6f", x[i]);
    }
    fila0[n + 1] = "-";
    iteraciones.add(fila0);
    
    int iter = 0;
    double error;
    
    do {
        for (int i = 0; i < n; i++) {
            xAnt[i] = x[i];
        }
        
        for (int i = 0; i < n; i++) {
            double suma = b[i];
            for (int j = 0; j < n; j++) {
                if (j != i) {
                    suma -= A[i][j] * x[j];
                }
            }
            x[i] = suma / A[i][i];
        }
        
        error = 0;
        for (int i = 0; i < n; i++) {
            error = Math.max(error, Math.abs(x[i] - xAnt[i]));
        }
        
        iter++;
        
       
        String[] fila = new String[n + 2];
        fila[0] = String.valueOf(iter);
        for (int i = 0; i < n; i++) {
            fila[i + 1] = String.format("%.6f", x[i]);
        }
        fila[n + 1] = String.format("%.6f", error);
        iteraciones.add(fila);
        
    } while (error > tol && iter < maxIter);
    
    if (error > tol) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Gauss-Seidel no convergio en " + maxIter + " iteraciones\nError final: " + error, 
            "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
 
    String[][] iterArray = new String[iteraciones.size()][];
    for (int i = 0; i < iteraciones.size(); i++) {
        iterArray[i] = iteraciones.get(i);
    }
    
    
    mostrarResultados(x, iterArray);
    
    return x;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
